### ISSUE TITLE
For production, does it make sense to add files to tmp local storage?

### ISSUE THREAD

**Issue by oscar-investmatic** [ImperialCollegeLondon/django-drf-filepond#110]
Hi Folks, 

I'm pretty sure that I'm missing something here, but I was basically under the idea that uploading and serving files from our Production Django installation is a big no no. 

Would it make sense to also have tmp files in AWS or any other storage? Else, curious to hear how you are using this and deploying it to production. 

Cheers

**Comment by oscar-investmatic** [comment]
Closing as I found similar discussion.

**Comment by jcohen02** [comment]
Thanks for the question @oscar-investmatic and glad you found some earlier discussion that helped to answer this.

A long planned update is to provide some form of support for using external storage services to support temporary uploads (in the same way that `django-storages` is used to provide support for "permanent" storage of uploads). There were some issues/challenges with this - maybe that's the previous issue/discussion that you encountered. For now, it's on the list of things it would be good to add into the library in the future.
