### ISSUE TITLE
Django 2 support?

### ISSUE THREAD

**Issue by daspecster** [ImperialCollegeLondon/django-drf-filepond#12]
Hello! Just curious if there's any plan to support Django 2+?

**Comment by jcohen02** [comment]
Hi, Django 2 is supported and used if you're using Python 3 (Django 2+ doesn't support Python 2.7 so Django 1.11 will be installed in that case).

The tests are passing with the latest Django 2.2 release. I'll therefore close this issue for now but if you're experiencing a specific problem getting the library to work with Django 2+, then feel free to re-open the issue with some further details of the problem. Thanks.

**Comment by daspecster** [comment]
Ah I missed that thank you!

I was having an issue with CSRF and a "bad request" response but I will dig into that a bit more and check back.

Thanks for the great project!
