### ISSUE TITLE
repository is vulnerable

### ISSUE THREAD

**Issue by icorgadmin** [ImperialCollegeLondon/django-drf-filepond#33]
A new security advisory was published 

We found a vulnerable dependency in repositories you have security alert access to.

Security advisory GHSA-vfq6-hq5r-27r6 (moderate severity) affects 1 repository: 

Django(pip) used in 1 repository    

   ImperialCollegeLondon/django-drf-filepond  
View alert  [https://github.com/ImperialCollegeLondon/django-drf-filepond/network/alert/setup.py/Django/open]

**Comment by jcohen02** [comment]
Fixed.
