### ISSUE TITLE
Feature request: Add custom upload field name

### ISSUE THREAD

**Issue by theyosh** [ImperialCollegeLondon/django-drf-filepond#4]
Hi,

we are using this django module with FilePond on our website. The issue we have right now is that we have multiple FilePond instances on our side. And therefore we have mutliple upload file fields.

As I look into the code of this Django module, there is no support for this? The upload field name has to be filepond always. This is not flexible for us.

So we made a very small code change at https://github.com/ImperialCollegeLondon/django-drf-filepond/blob/master/django_drf_filepond/views.py#L62:

```
file_id = _get_file_id()
upload_id = _get_file_id()
        
if 'filepond' not in request.data:
    raise ParseError("Invalid request data has been provided.")
            
file_obj = request.data['filepond']
```

To:

```
file_id = _get_file_id()
upload_id = _get_file_id()

upload_field = 'filepond'
if 'fp_upload_field' in request.data:
    upload_field = request.data['fp_upload_field']

if upload_field not in request.data:
    raise ParseError("Invalid request data has been provided.")

file_obj = request.data[upload_field]
```

Then we extend the FilePond srver processing code with:

```
server: {
      url: '/fp',
      process: {
        url: '/process/',
        method: 'POST',
        headers: {
          'X-CSRFToken': $('input[name="csrfmiddlewaretoken"]').val()
        },
        withCredentials: false,
        ondata: (formData) => {
          var upload_field = '';
          for (var item of formData.keys()) {
            upload_field = item;
            break;
          }
          if (upload_field !== '') {
            formData.append('fp_upload_field',upload_field);
          }
          return formData;
        },
        onerror: (response) => { console.log(response.data); },
      }
}
```

The above javascript will inject the extra form field 'fp_upload_field' with the value of the FilePond file field name. And this works like a charm for us.

So is it possible to extend the view.py with an extra check for an extra field containing the file upload field name?

**Comment by jcohen02** [comment]
Hi,

Happy to add support for filepond instances with IDs other than `filepond` to support multiple filepond instances on a given page (or just the case where a developer has opted to use a name other than filepond for their filepond element). This seems like a useful extension.

Presumably you don't need to know at a later time which instance uploaded a given file? The database could be updated to record the source filepond instance when an upload is stored but if this is not required at present, I'd be inclined not to do this for now in order to maintain simplicity.

**Comment by theyosh** [comment]
Hi,

you are correct in your second part. We only need the option to specify the upload form field name. When the file is uploaded, we can just handle the TemporaryUpload and use the ID that is returned.

There is no need to store the field name in a DB.

**Comment by jcohen02** [comment]
Just added an update for this.

@theyosh, if this looks ok, I'll include this in the next release.

**Comment by jcohen02** [comment]
This is now available, along with tests and some info added to the docs, in [release v0.0.5](https://github.com/ImperialCollegeLondon/django-drf-filepond/releases/tag/v0.0.5). I'll close the issue for now but feel free to re-open if this doesn't provide what you were after.

**Comment by theyosh** [comment]
@jcohen02 Just did an update with pip. It does work like expected, as we had this patch already running. And we do not see any issues. Thanks for the fast addition.

**Comment by jcohen02** [comment]
@theyosh glad this works, thanks for the feedback and for using the library.
