### ISSUE TITLE
VueJS - {"detail": "Invalid request data has been provided."}

### ISSUE THREAD

**Issue by hvitis** [ImperialCollegeLondon/django-drf-filepond#44]
Hello!

I was trying to set up vue-filepond with DRF and I keep getting this message after uploading photo on front end and on POSTMAN. I went through the tutorial on the page, I set up server options on Django and on Vue.

Is there any way of tracing the error better / making it more verbose? 
Is there any collection of POSTMAN requests for a simple server setup?

Thank you for any suggestions.

**Comment by hvitis** [comment]
**Solved it:**

In uploaders.py there is a classmethod:

```
    @classmethod
    def _get_file_obj(cls, request):
        
        upload_field_name = 'filepond'
        if 'fp_upload_field' in request.data:
            upload_field_name = request.data['fp_upload_field']

        if upload_field_name not in request.data:
            raise ParseError('Invalid request data has been provided.')

        file_obj = request.data[upload_field_name]

        return file_obj
```

Which sais that the key with file should be called __filepond__ so I tested it with POSTMAN uploading a file with form-data and it worked! This is the request in axios:

```
var axios = require('axios');
var FormData = require('form-data');
var fs = require('fs');
var data = new FormData();
data.append('filepond', fs.createReadStream('/Users/hvitis/Downloads/SAMPLE_PICTURE.png'));

var config = {
  method: 'post',
  url: 'http://localhost:8000/fp/process/',
  headers: { 
    ...data.getHeaders()
  },
  data : data
};

axios(config)
.then(function (response) {
  console.log(JSON.stringify(response.data));
})
.catch(function (error) {
  console.log(error);
});

```

But the crucial solution in __VUEJS__ was to change the __name__ attribute's value to __filepond__:

```
<file-pond
          name="filepond"
          ref="pond"
          label-idle="Drop files here..."
          v-bind:allow-multiple="false"
          accepted-file-types="image/jpeg, image/png, image/jpg"
          v-bind:files="myFiles"
          v-on:init="handleFilePondInit"
          :server="serverOptions"
        />
```

**Comment by hvitis** [comment]
PS: My logger was also not working that's why I didn't get the tutorials Logger explanation to work. 
Working logger here:

```

# Loggin the info
import logging.config
LOGGING_CONFIG = None
logging.config.dictConfig({
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'console': {
            # exact format is not important, this is the minimum information
            'format': '%(asctime)s %(name)-12s %(levelname)-8s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'console',
        },
    },
    'loggers': {
        # root logger
        '': {
            'level': 'DEBUG',
            'handlers': ['console'],
        },
        'django_drf_filepond.views': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django_drf_filepond.models': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django_drf_filepond.uploaders': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        
    }
})
```

**Comment by jcohen02** [comment]
Hi @hvitis, thanks for raising this issue and also for updating with your solution.

The use of `filepond` as the default field name was based on the default value for the `name` property in the [Filepond instance properties](https://pqina.nl/filepond/docs/patterns/api/filepond-instance/#properties). #4 updated this to allow the use of other names for the filepond instance by setting the `fp_upload_field` property in the `POST` data.

I presume you're using the [vue-filepond](https://github.com/pqina/vue-filepond) adapter? I've not used this myself but I note in the example that the object name is set as `test` rather than `filepond`. If you want to use a different name, I presume it's possible to inject an `fp_upload_field` parameter into the request sent via the vue adapter but I'd have to investigate.

Glad you managed to solve the problem. If you have any suggestions as to updates that can be made to the documentation to clarify things with this, do let me know and I can look to add something (or feel free to raise a PR).

Otherwise, let me know if you're happy for this issue to be closed now.

**Comment by hvitis** [comment]
Hello @jcohen02 

Thank you very much for a quick and explanatory reply! Indeed I am using the __vue-filepond__ adapter. I will try making pull request there to change the default name so that it matches the FilePond documentation. This misleading small little detail can cost other people time too.

Indeed it is possible to inject custom field name as you said! Here it is working:

<img width="458" alt="Screenshot 2020-08-17 at 15 20 35" src="https://user-images.githubusercontent.com/17104239/90400749-38768480-e09d-11ea-8f59-280aeea9ad89.png">

I think that the issue is just a small mistake on my side due to the vue-adapter example so it can be closed.

I would have just a last question, not really relevant to this issue so please let me know if I should raise a new issue:

How the process of saving pictures to local/cloud storage should be done because I do not fully understand it:
- Should I make a separate API call and use the shortUUIDs saved in hidden input on vue-filepond after making the POST call ?
or
- I should extend the POST ProcessView in order to save the file? I think this approach would be contradictory to the Revert option that this repo offers when canceling the uploaded picture on front end (or should I follow up on that and use extended RevertView or 

I mean I don't have a clear picture of a simple flow and I am wondering how to move forward from the __store_upload__ example.

**Comment by jcohen02** [comment]
> I think that the issue is just a small mistake on my side due to the vue-adapter example so it can be closed.

Ok, no problem, thanks, I'll close the issue once any follow up discussion to this is concluded. 

I understand that there's quite a bit to learn here if you're new to working with `filepond` and it's different adapters so I'll also look to put a note in the documentation about the use of the filepond vue adapter, just in case that helps anyone else from getting caught out with a similar issue.

Regarding the workflow, `django-drf-filepond` helps with two aspects:

 1. Directly handling file uploads sent via the filepond UI, implementing Filepond's server-side API as documented [here](https://pqina.nl/filepond/docs/patterns/api/server/).
 1. Providing a simple server-side API for storing/managing uploaded files within the context of your application, but using an approach that subsequently allows you to use filepond's `load` endpoint to access stored files. Local and cloud-based storage options are provided.

I think the thing to clarify here is that files can be in two states - _temporary upload_ and _stored upload_. My understanding is that filepond, and filepond server API, get a file from a client onto the server as a _temporary upload_. It's then the job of your application to store temporary uploads as _stored uploads_ if you need to. `django-drf-filepond`'s API (via the `store_upload` function) helps with this. _Note temporary uploads are currently only stored on local storage on your app server, cloud storage of temporary uploads is not yet supported._

So, assuming you have a web application with a user interface and a Django backend with some server-side endpoints, and you want to add file upload via filepond:
 - You add a form into which you embed filepond. The form may well also have a number of other fields in addition to file upload.
 - The assumption here is that you are configuring filepond to upload a file as soon as it is selected (although you can control that via the options).
 - When a file is added to filepond, it immediately sends a `process` request that is handled by `django-drf-filepond`. You now have a _temporary upload_ on the server side. `django-drf-filepond` sends back a unique ID which filepond embeds in the form in your UI.
 - You then submit the form, potentially including other fields related to your application. This form submission is handled by an endpoint in _your application_. When your application handles the form POST request, it receive's the unique IDs of any filepond uploads that were made through the filepond widget associated with that form.
 - Given the one or more filepond IDs, you can then look up in the database the `TemporaryUpload` object(s) relating to the ID(s) received and handle them yourself, or use the `django-drf-filepond` API.
 - You can either write your own logic in your application to do something with the temporary uploads (e.g. get the path from the `TemporaryUpload` object and copy the file(s) somewhere else for permanent storage and access by your application (and don't forget to delete the `TemporaryUpload` object). Or you can use the `store_upload` function provided by `django-drf-filepond` to save the file(s) to local or cloud storage. Stored files are then associated with a `django-drf-filepond` StoredUpload object. Using this approach you can subsequently use filepond's `load` API function to load the file into filepond's UI if necessary.
 - By using a `StoredUpload` object, you also don't need to write your own logic to manage stored file uploads, you can use `django-drf-filepond`'s [`get_stored_upload`](https://github.com/ImperialCollegeLondon/django-drf-filepond#22-get_stored_upload--get_stored_upload_file_data), [`get_stored_upload_file_data`](https://github.com/ImperialCollegeLondon/django-drf-filepond#22-get_stored_upload--get_stored_upload_file_data) and [`delete_stored_upload`](https://github.com/ImperialCollegeLondon/django-drf-filepond#23-delete_stored_upload) functions to manage uploaded files.

Apologies if some of the the above is stating the obvious - hope I didn't misunderstand your question - however, I hope this is some help. If you'd like further clarification, let me know. Also, if you think it might be useful to write some of this up and include it in the documentation, I can look to do that soon.

**Comment by hvitis** [comment]
The idea of filepond, editor, plugins that comes with an adapter for vue AND backend with great architecture got me hooked so much that I was reading the __django-drf-filepond__ package and I arrived to a similar conclusions which makes me really happy.

A lot of happines gave me also your very thoutugh reply which is exactly what I needed. I can't thank you enough. I would love to contribute in some way to thank you. Is there a Donate button somewhere or is there a list of potential improvements that could be done with PR?

What comes to my mind after some investigating and brief usage is that there is a room for improvement when it comes to error handling in Responses. For example the issue that caused me to wonder what is wrong was giving me a vague "Invalid request data" information where it could return e.g. "provided key incorrect". Can I try to add such small things and make a PR?

Also I keep a blog with solutions like this and with interesting libraries etc. Would you mind if I copied part of the message you mentioned in a post about __django-drf-filepond__? I could link any source you wish. That would be of a great help too, there is not many tutorials online on __django-drf-filepond__ which is a shame cause I really like the solutions. It's smooth.

This issue can be closed. Thank you again for your time 👋. Have a great day!

**Comment by jcohen02** [comment]
Many thanks @hvitis, great to hear that the information was what you were looking for and many thanks too for the offer to contribute.

Certainly no need to contribute - it's good to know that the library is being used and it's useful. At the same time any contributions to the library are always appreciated so if you'd like to provide any fixes to improve the error reporting, then please do feel free to go ahead and create a PR when you have a chance. I'm also always happy to receive any suggestions of how the documentation can be improved, pointers to any errors, or PRs with updates to the documentation if you've spotted anything that you'd like to fix.

I should also thank the developer of [filepond](https://github.com/pqina/filepond) who has put a vast amount more work into developing a great file upload plugin than I've put into this small backend library, and without which `django-drf-filepond` wouldn't exist! 🙂 

Re your blog, if you'd like to use some text from this issue, that's fine and thanks for checking. For now, probably easiest to just provide a link back to the specific post in this thread that you're using the text from ([this one](https://github.com/ImperialCollegeLondon/django-drf-filepond/issues/44#issuecomment-674998693) I presume). If the text subsequently gets written up into the documentation then you could update the link to point to that if that's a better source.

Thanks again and I'll close this issue now. 👋

**Comment by hvitis** [comment]
I wrote some more explanation on this [here](https://hvitis.dev/how-to-upload-files-with-filepond-and-drf-extension).

**Comment by jcohen02** [comment]
Great tutorial, many thanks for writing this up and highlighting `django_drf_filepond`. I'm sure this will be very useful to people working with Filepond, VueJS and a Django backend. 🙂
