### ISSUE TITLE
How to make thumbnail for a stored_upload?

### ISSUE THREAD

**Issue by 7iomka** [ImperialCollegeLondon/django-drf-filepond#52]
Hi
I want to use
`from sorl.thumbnail import get_thumbnail`

`su = get_stored_upload(upload_id)`

how to make & store thumnails for existing upload?
I need to do something so that they are done automatically when created and deleted when deleted
Thanks

**Comment by jcohen02** [comment]
Hi,

I'm not actually familiar with `sorl.thumbnail` but `get_stored_upload` gets you a `django_drf_filepond.models.StoredUpload` instance which contains `file` which is a `FileField`, so effectively a wrapper around the stored upload file.

I've just tested the following with `sorl.thumbnail` which seems to work fine:

```python
from django_drf_filepond.api import get_stored_upload
from sorl.thumbnail import get_thumbnail

# The unique upload ID for the stored upload that you want to create a thumbnail from
upload_id = 'UNIQUE_UPLOAD_ID'

su = get_stored_upload(upload_id)

with su.file.open() as f:
    im = get_thumbnail(f, '150x150', crop='center', quality=80)
```

`im` is now a `sorl.thumbnail.images.ImageFile` object that seems to represent the thumbnail image that has already been stored to a location managed by `sorl.thumbnail`. I presume this is controllable via the `sorl.thumbnail` library settings.

Hope this helps and answers your question.
