### ISSUE TITLE
Setting for less restrictive file permissions

### ISSUE THREAD

**Issue by derek-adair** [ImperialCollegeLondon/django-drf-filepond#77]
This has become an impediment in development for me.  It would be nice to be able to have open file permissions as an django setting.

Also I am having trouble figuring out what 'mode' even is in os.mkdirs().

**Comment by jcohen02** [comment]
Hi @derek-adair, apologies for the very slow response on this, the issue got missed amidst an extremely busy period!

When you say "_would be nice to be able to have open file permissions as an django setting._", can you ellaborate? Do you mean you want to be able to set file permissions when storing an upload?

> Also I am having trouble figuring out what 'mode' even is in os.mkdirs().

Did you mean you're not clear on the meaning of the 3-digit octal code defining the (Unix-style) permissions of a directory when creating this? (Not sure what platform(s) you're developing on...)

Apologies if I'm misunderstanding.

**Comment by derek-adair** [comment]
Yes, specifically for development purposes.  When I need to rebuild my docker image the tmp directory is unable to be deleted.  At least i think thats the directory (can't replicate it at the moment).  I see that there is a setting to delete the tmp directory, maybe thats the solution.  I'll get back to you on this.

> Did you mean you're not clear on the meaning of the 3-digit octal code defining the (Unix-style) permissions of a directory when creating this? (Not sure what platform(s) you're developing on...)

Oooo so thats just like unix perms.  Got it.  I'm not sure why i asked that, i can't find os.mkdirs() in this code base anymore, not sure what or where i got that from.

**Comment by jcohen02** [comment]
@derek-adair, I'm assuming this was resolved is no longer an issue so I'm going to close this - feel free to reopen if you have further questions/feedback or if this is still causing an issue for you. Thanks.

**Comment by derek-adair** [comment]
Not really but i've not had time to work on this project.  I need to be able to easily delete and/or cleanse the upload directory and i'm not sure where these permissions are set.
