### ISSUE TITLE
Multiple images

### ISSUE THREAD

**Issue by hvitis** [ImperialCollegeLondon/django-drf-filepond#79]
Hello,

I am using VueJS front-end plugin and DRF on backend. FE allows uploading drag-drop multiple images and I was thinking about expanding my 1 picture and making a gallery for a model.

Is it possible to save multiple images via DRF-filepond? I am using AWS

**Comment by derek-adair** [comment]
Yes.... but this is not really relevant to DRF-filepond.  This is logic that will take place in your view, model or form.

**Comment by jcohen02** [comment]
Thanks for the question @hvitis. As @derek-adair says, I wonder if this is perhaps better handled via your backend configuration/code?

Effectively, you'd allow the frontend to upload all the images via filepond, with each image upload returning a unique ID for the temporary upload record generated. Then when you submit the upload of the gallery, you'd handle storing and grouping the individual uploads under perhaps a `Gallery` model or similar, which has references to all the `StoredUpload` objects related to that gallery. Hope that makes sense?

**Comment by jcohen02** [comment]
I'm going to close this issue but please follow-up if you have further questions on this.
